### ISSUE TITLE
repair methodsの数を増やす (APRNN)

### ISSUE THREAD

**Issue by y629** [posl/DNN-repair-break-prediction#14]
モデル対象の手法のみを増やす．
コード対象にしない理由は文章で補強する必要がある．

**Comment by y629** [comment]
PRDNN (PLDI'21) の続きの研究であるAPRNN (PLDI'23) を使う

APRNNのレポジトリにPRDNNともう1つ実装されてるそうなのでワンチャン3つ増やせる．
けどこれらは全部provable系なので毛色が少し違うのがネック

**Comment by y629** [comment]
# APRNNの再現実験メモ
このイシューの以下ポストは全部これ関連です．

パッケージのURL: 
- https://github.com/95616ARG/APRNN

ACAS XUの実験を行うには？
- `eval_4_*.py` すればいける．`*` の部分は3種類の手法が入る．
- しかし以下のようなエラーになる．

```
Traceback (most recent call last):
  File "/aprnn_pldi23/tutorial.py", line 24, in <module>
    import sytorch as st
  File "/aprnn_pldi23/sytorch/__init__.py", line 49, in <module>
    from .nn import no_symbolic
  File "/aprnn_pldi23/sytorch/nn/__init__.py", line 2, in <module>
    from .parameter import *
  File "/aprnn_pldi23/sytorch/nn/parameter.py", line 10, in <module>
    from sytorch.pervasives import Interval
```

`tutorial.py` に簡単な例と豊富なコメントがある．sytorchは著者らがtorchを拡張して記号実行に対応できるようにしたやつらしい．torchのメソッドはすべて引き継いでるらしい．

`Interval` というクラスを使っている関数 `_fuse_for_argmax_exact`  が呼び出されてないのでいらないと思う．一回コメントアウトする

**Comment by y629** [comment]
修正済みのモデルをpth形式で得ることはできそう．なのでそれを今回の研究のモデルクラスの形式に微調整すればrepaired modelsを入手可能．

懸念としては，repaired modelsを取得するために使ったデータセットが違う
- APRNNの方は入力の制約条件をパーティションしてサンプリング
- CAREの方は入力範囲から正例と負例を一定数ランダムサンプリング

**Comment by y629** [comment]
問題はrepsやfoldsがAPRNNだと作れなかったり，修正に実際に使うデータが微妙に違う点．ここをどのように論文中で書くかはまた考えないといけない

**Comment by y629** [comment]
APRNN側のseedを変えるようにすればrepsは同じだけ取れるかも．だけどfoldsはデータセットの分割に関するものなので無理．この辺は手法の違いに起因するものなのでどうしようもない

**Comment by y629** [comment]
N1,9はメモリ使いすぎてクラッシュしてしまうのでなんとかしたい．それか対象から外しちゃいたい

**Comment by y629** [comment]
seedを5種類変えてAPRNNの修正済みモデルを1種類につき5つ得られるようにした

**Comment by y629** [comment]
`src/safety` 直下に `check_aprnn.py`  的なのを作って，APRNNに対するrepair/break datasetを作りたい．
repairやbreakに関しては同様に5モデルの予測結果を使って決める．
このデータセットさえできればあとは同じことすればいける

**Comment by y629** [comment]
全部repairできたのでrepair pred modelは作れない

**Comment by y629** [comment]
手法の選択の話に持ってくのがむずい
全部repairできるなら，repaired sampleを多く求める開発者にとってはそれがベストなのでpred modelいらなくなる

**Comment by y629** [comment]
PRDNNを追加しようと思ったけどできなかった
理由は，architecture-preservingではないから推論が同様にできない
